### PR TITLE
Fix DDC reliability on latest Xcode versions, migrate to SPM, more fixes

### LINKED ISSUE #238: DDC commands not being issued reliably when building with Xcode > 11.3.1
On recent versions of Xcode, I get some reliability issues with DDC in MonitorControl. I'm not sure why this is happing but I'm wondering if anyone else is running into this too.

Note: I haven't tested all the versions after 11.3.1 but current last version (11.5 and the one version below that don't work for me).

### LINKED ISSUE #448: Fix dependencies
- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
I tried cloning the project and building it myself and I ran into several issues all boiling down to the fact that the Cartfile has no versions/commit hashes set:

- AMCoreAudio is not called SimplyCoreAudio on version 4 and no longer source compatible with version 3 (AMCoreAudio) which is what this project uses. So the Cartfile should specify the version as `~> 3.4`.
- DDC and MediaKeyTap simply use `master` in the Cartfile. This is an issue because after I fixed the AVMCoreAudio problem I noticed that the app I compiled myself doesn't work properly – most of the time nothing changes on my display. Only after spamming volume/brightness keys anything starts to change. The latest version installed through homebrew does not have this problem. This could be a regression in `DDC`, but since there is no commit information/tag version for DDC in the Cartfile I do not know which commit you linked against!

**Environment Information (please complete the following information):**

- macOS version: 11.4
- Mac model: 2019 MBP
- MonitorControl version: master
- Monitor(s): LG HDR 5K
- Apple Silicon/M1 (yes or no): no

### PR DESCRIPTION
**Pull request by JoniVR**
## Description

This PR makes the following changes:
* Migrate from Carthage to Swift Package Manager for dependency management
* Fix reliability issues for DDC in latest Xcode versions (#238)
* Update README with new steps and screenshots
* Updated preferences pane to be more in line with Big Sur style.
* Migrated from AMCoreAudio -> [SimplyCoreAudio](https://github.com/rnine/SimplyCoreAudio) (same framework, different name).
* Migrated from [MASPreferences](https://github.com/shpakovski/MASPreferences) -> [Preferences](https://github.com/sindresorhus/Preferences)
* Updated DDC.swift, MediaKeyTap (DDC.swift update should improve reliability for **some** identical monitors #49, thanks @leo150)
* Uses `NSGridView` for preferences layout.

This PR is mostly needed so we can actually have a working build again (and hopefully merge some of the open PRs that have been blocked by this). It will probably introduce some conflicts in other PRs (storyboard hell) but still seems necessary in order to test them reliably.

Fixes #238
Closes #448

image

### CODE REVIEW

**Comment by the0neyouseek** [comment]
As always, thanks for the awesome work @JoniVR 
I'll look into reviewing this on Monday

File: MonitorControl/Extensions/Preferences+Extension.swift [hunk 1]
```diff
@@ -0,0 +1,16 @@
+//
+//  Preferences+Extension.swift
+//  MonitorControl
+//
+//  Created by Joni Van Roost on 22/11/2020.
+//  Copyright © 2020 Guillaume Broder. All rights reserved.
```
Comment (the0neyouseek) [inline MonitorControl/Extensions/Preferences+Extension.swift:6]: We should remove my name from the "Organization" field in the xcodeproj to remove copyright mentions when generating new files. (And also remove them from current files in the future

**Review by the0neyouseek — APPROVED** [review]
Everything looks good to me ! Great job as always 👌

File: MonitorControl/Extensions/Preferences+Extension.swift (hunk 1 above)
Comment (JoniVR) [reply MonitorControl/Extensions/Preferences+Extension.swift]: Done 🙂 The only place I haven't updated is the bundle identifier since I thought that'd probably have an impact on other things.
